name: amix_database
description: A package for Saving your Data inside local System.
version: 0.0.1
homepage: https://github.com/peter-parker-a/amix_database

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
